runtime: python39
instance_class: B8
env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "project/interface.py"
  GPU_WORKER_TIMEOUT: 10
  NUM_GPU_WORKERS: 1
  EGG_COUNTING_BACKEND_TYPE: "gcp"
basic_scaling:
  max_instances: 2
entrypoint: python3 -m project.server --host 0.0.0.0 --port 8080
